version: '3.8'

services:

  frontend:
    image: matheuspieropan/proposta-web
    container_name: proposta-web-container
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:16
    container_name: postgres-proposta-web-container
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-proposta-web-container
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge